update extract function

diff --git a/shell/functions b/shell/functions
--- a/shell/functions
+++ b/shell/functions
@@ -18,6 +18,7 @@ pathmunge() {
 #[ -d "/usr/local/mysql" ] && pathmunge "/usr/local/mysql/bin" "after"
 #[ -d "/Users/xinyi/Workspace/android-sdks/platform-tools" ] && pathmunge "/Users/xinyi/Workspace/android-sdks/platform-tools" "after"
 [ -d "/Applications/Qt/Qt5.1.1/5.1.1/clang_64/bin" ] && pathmunge "/Applications/Qt/Qt5.1.1/5.1.1/clang_64/bin" "after"
+[[ -d "/Applications/TeX/texlive/2013basic/bin/x86_64-darwin" ]] && pathmunge "/Applications/TeX/texlive/2013basic/bin/x86_64-darwin" "after"
 unset pathmunge
 
 man () {
@@ -80,37 +81,36 @@ function rename() {
 #	else
 #		echo "extract needs $prog, but not exist"
 #	fi
-extract() {
-	if [ -f $1 ]; then
-		case $1 in
-			*.tar.bz2|*.tbz|*.tbz2)
-				tar xjf $1
-				;;
-			*.tar.gz|*.tgz)	tar xzf $1
-				;;
-			*.bz2)			bunzip2 $1
-				;;
-			*.rar)			unrar x $1
-				;;
-			*.gz) 			gunzip $1
-				;;
-			*.tar)			tar xf $1
-				;;
-			*.zip|*.war|*.jar)
-				unzip $1
-				;;
-			*.Z)			uncompress $1
-				;;
-			*.xz)			xz --decompress $1
-				;;
-			*)				echo "'$1' cannot be extracted via extract"
-				;;
-		esac
-	else
-		echo "extract: '$1' is not a valid file"
-	fi
+extract () {
+    while (( $# > 0 )); do
+        echo $@
+	    if [[ -f $1 ]]
+	    then
+		    case $1 in
+			  *.tar.bz2|*.tbz|*.tbz2) tar xjf $1 ;;
+			  *.tar.gz|*.tgz) tar xzf $1 ;;
+			  *.bz2) bunzip2 $1 ;;
+			  *.rar) unrar x $1 ;;
+			  *.gz) gunzip $1 ;;
+			  *.tar) tar xf $1 ;;
+			  *.zip|*.war|*.jar) unzip $1 ;;
+			  *.tar.Z) uncompress $1; set -- $@ ${1:0:-2} ;;
+              *.Z) uncompress $1 ;;
+              *.tar.xz) xz --decompress $1; set -- $@ ${1:0:-3} ;;
+              *.txz) mv $1 ${1:0:-4}.tar.xz; set -- $@ ${1:0:-4}.tar.xz ;;
+			  *.xz) xz --decompress $1 ;;
+              *.7z) 7za x $1 ;;
+              *.rar) unrar x ad $1 ;;
+			  *) echo "'$1' cannot be extracted via extract" 1>&2 ;;
+		    esac
+	    else
+		    echo "extract: '$1' is not a valid file" 1>&2
+	    fi
+        shift
+    done
 }
-compdef '_files -g "*.gz *.tgz *.bz2 *.tbz *.zip *.rar *.tar *.lha"' extract
+
+compdef '_files -g "*.gz *.tgz *.txz *.xz *.7z *.Z *.bz2 *.tbz *.zip *.rar *.tar *.lha"' extract
 
 # History accepts a range in zsh entries as [first] [last] arguments, so to
 # get them all run history 1.
