add new function rename to shell/functions; add shell-type.sh to tell which type of shell is invoking

diff --git a/shell/functions b/shell/functions
--- a/shell/functions
+++ b/shell/functions
@@ -56,6 +56,17 @@ ips() {
 	ifconfig | grep "inet" | awk '{print $2}'
 }
 
+# rename file or directory
+function rename() {
+	[[ $# -eq 2 ]] || { echo "Usage: rename <old_name> <new_name>"; return 1; }
+	[[ $# -eq 2 ]] || { echo "Usage: $0 <old_name> <new_name>" ; return 1; }
+	[ -e "$1" ] || { echo "No such file or directory:" $1; return 1; }
+	[ "$1" != "$2" ] || { echo the same name; return 1; }
+	mv -i $1 $2
+	[ $? -eq 0 ] || { echo "rename error"; return 1; }
+	return 0
+}
+
 # extract files from compressed status
 extract() {
 	if [ -f $1 ]; then
